#!/bin/env ruby

require 'optparse'
require 'pp'
require 'csv'

OPTIONS = {
  :buffer => 50,
  :verbose => false,
  :geotiff => %w{ -co TILED=YES -co COMPRESS=LZW }
}

ARGV.options do |o|
  script_name = File.basename($0)
  o.banner = "Usage: #{script_name} [OPTIONS] INPUT_CSV OUTPUT_DIR"
  o.define_head "describe it ya.."
  o.separator ""
  o.on("-b", "--buffer=[int]", Integer, 
      "box size in KM. Default: #{OPTIONS[:buffer]}") { |b| OPTIONS[:buffer]=b }
  o.on("-v", "--verbose", "be verbose") { |v| OPTIONS[:verbose] = v }
  o.separator ""
  o.on_tail("-h","--help","Show this help.") { puts o; exit }
  HELP=o.to_s
end

VERBOSE=OPTIONS[:verbose]

puts "buffer: #{OPTIONS[:buffer]}" if VERBOSE

input_file = ARGV.shift || raise("missing input CVS")
output_dir = ARGV.shift || raise("missing output directory")

unless File.directory?('sources')
  puts "FATAL: no 'sources' folder found."
  puts "I expect to look in a sources folder and extract from the files there"
  exit 1
end

sources = Dir.entries('sources').map { |f| f if File.directory?(f) }.compact

if sources.size < 1 
  puts "ERROR: no images in sources directory to work with"
  exit 1
end
puts "found #{sources.size} source images: #{sources.join(", ")}"

# load up and loop through the CSV file reporting
# the name/x/y of each as a sanity check for ourselves.
# and shoving the valid ones into targets array:
targets = [] # array of hashes: { :name =>, :x =>, :y }

csv = CSV.open(input_file, 'r', :headers=>:first_row)
csv.each do |row|
  puts row[0] + "," + row[1] + "," + row[2]
  targets.push({ :name => row[0], :x => row[1].to_f, :y => row[2].to_f })
end

def gdal_translate(target,source,output)
# gdal_translate -projwin (bounding box) (source) (output)
# real example 
#  gdal_translate -projwin -218505 733188 -217487 732413 input.vrt output.tif 
#  boundbox is: upper left, lower left, upper right, lower right
  b = OPTIONS[:buffer]/2
  x = target[:x]
  y = target[:y]
  bbox = [ x-b, y+b, x+b, y-b ]
  cmd = %w{ gdal_tranlsate -projwin } + OPTIONS[:geotiff] + 
        bbox + [ source, output ]
  #system(*cmd)
  puts ">> " + cmd.join(" ")
end
